# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='transit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x07transit\"O\n\x0cStopPosition\x12\x0f\n\x07stop_id\x18\x01 \x01(\x07\x12\x11\n\tstop_time\x18\x02 \x01(\x07\x12\x1b\n\x13shape_dist_traveled\x18\x03 \x01(\x02\"h\n\x07\x42usInfo\x12\x0f\n\x07trip_id\x18\x01 \x01(\x05\x12&\n\x06shapes\x18\x02 \x03(\x0b\x32\x16.transit.ShapePosition\x12$\n\x05stops\x18\x03 \x03(\x0b\x32\x15.transit.StopPosition\"*\n\nBusInfoCol\x12\x1c\n\x02\x62i\x18\x01 \x03(\x0b\x32\x10.transit.BusInfo\"-\n\x04Test\x12%\n\x05shape\x18\x01 \x01(\x0b\x32\x16.transit.ShapePosition\"F\n\rShapePosition\x12\x1b\n\x13shape_dist_traveled\x18\x01 \x01(\x02\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0b\n\x03lon\x18\x03 \x01(\x02\x62\x06proto3'
)




_STOPPOSITION = _descriptor.Descriptor(
  name='StopPosition',
  full_name='transit.StopPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stop_id', full_name='transit.StopPosition.stop_id', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop_time', full_name='transit.StopPosition.stop_time', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape_dist_traveled', full_name='transit.StopPosition.shape_dist_traveled', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=102,
)


_BUSINFO = _descriptor.Descriptor(
  name='BusInfo',
  full_name='transit.BusInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trip_id', full_name='transit.BusInfo.trip_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shapes', full_name='transit.BusInfo.shapes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stops', full_name='transit.BusInfo.stops', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=208,
)


_BUSINFOCOL = _descriptor.Descriptor(
  name='BusInfoCol',
  full_name='transit.BusInfoCol',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bi', full_name='transit.BusInfoCol.bi', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=252,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='transit.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='transit.Test.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=299,
)


_SHAPEPOSITION = _descriptor.Descriptor(
  name='ShapePosition',
  full_name='transit.ShapePosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape_dist_traveled', full_name='transit.ShapePosition.shape_dist_traveled', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='transit.ShapePosition.lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lon', full_name='transit.ShapePosition.lon', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=371,
)

_BUSINFO.fields_by_name['shapes'].message_type = _SHAPEPOSITION
_BUSINFO.fields_by_name['stops'].message_type = _STOPPOSITION
_BUSINFOCOL.fields_by_name['bi'].message_type = _BUSINFO
_TEST.fields_by_name['shape'].message_type = _SHAPEPOSITION
DESCRIPTOR.message_types_by_name['StopPosition'] = _STOPPOSITION
DESCRIPTOR.message_types_by_name['BusInfo'] = _BUSINFO
DESCRIPTOR.message_types_by_name['BusInfoCol'] = _BUSINFOCOL
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['ShapePosition'] = _SHAPEPOSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopPosition = _reflection.GeneratedProtocolMessageType('StopPosition', (_message.Message,), {
  'DESCRIPTOR' : _STOPPOSITION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:transit.StopPosition)
  })
_sym_db.RegisterMessage(StopPosition)

BusInfo = _reflection.GeneratedProtocolMessageType('BusInfo', (_message.Message,), {
  'DESCRIPTOR' : _BUSINFO,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:transit.BusInfo)
  })
_sym_db.RegisterMessage(BusInfo)

BusInfoCol = _reflection.GeneratedProtocolMessageType('BusInfoCol', (_message.Message,), {
  'DESCRIPTOR' : _BUSINFOCOL,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:transit.BusInfoCol)
  })
_sym_db.RegisterMessage(BusInfoCol)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:transit.Test)
  })
_sym_db.RegisterMessage(Test)

ShapePosition = _reflection.GeneratedProtocolMessageType('ShapePosition', (_message.Message,), {
  'DESCRIPTOR' : _SHAPEPOSITION,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:transit.ShapePosition)
  })
_sym_db.RegisterMessage(ShapePosition)


# @@protoc_insertion_point(module_scope)
